name: Skywars
version: '${version}'
main: dev.deann.MinigameServer
api-version: '1.20'

commands:
  start:
    description: Start a Skywars game
    usage: /start
    aliases: [start]
  stopGame:
    description: Stop an active game
    usage: /stopGame
    aliases: [stopGame]
  queue:
    description: Join the game queue
    usage: /queue
    aliases: [queue]
